# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: keysight_chakra/infra/annotate.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'keysight_chakra/infra/annotate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$keysight_chakra/infra/annotate.proto\x12\x15keysight_chakra.infra\x1a\x19google/protobuf/any.proto\"9\n\x04\x44\x61ta\x12\x0c\n\x04name\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"\xa1\x02\n\x06Target\x12\x18\n\x0einfrastructure\x18\x01 \x01(\tH\x00\x12\x10\n\x06\x64\x65vice\x18\x02 \x01(\tH\x00\x12\x1a\n\x10\x64\x65vice_component\x18\x03 \x01(\tH\x00\x12 \n\x16\x64\x65vice_component_index\x18\x04 \x01(\tH\x00\x12\x19\n\x0f\x64\x65vice_instance\x18\x05 \x01(\tH\x00\x12\x1f\n\x15\x64\x65vice_instance_index\x18\x06 \x01(\tH\x00\x12)\n\x1f\x64\x65vice_instance_index_component\x18\x07 \x01(\tH\x00\x12/\n%device_instance_index_component_index\x18\x08 \x01(\tH\x00\x42\x15\n\x13infrastructure_path\"g\n\nAnnotation\x12.\n\x07targets\x18\x01 \x03(\x0b\x32\x1d.keysight_chakra.infra.Target\x12)\n\x04\x64\x61ta\x18\x64 \x01(\x0b\x32\x1b.keysight_chakra.infra.Datab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'keysight_chakra.infra.annotate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATA']._serialized_start=90
  _globals['_DATA']._serialized_end=147
  _globals['_TARGET']._serialized_start=150
  _globals['_TARGET']._serialized_end=439
  _globals['_ANNOTATION']._serialized_start=441
  _globals['_ANNOTATION']._serialized_end=544
# @@protoc_insertion_point(module_scope)
