# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: keysight_chakra/infra/service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'keysight_chakra/infra/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from keysight_chakra.infra import infra_pb2 as keysight__chakra_dot_infra_dot_infra__pb2
from keysight_chakra.infra import annotate_pb2 as keysight__chakra_dot_infra_dot_annotate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#keysight_chakra/infra/service.proto\x12\x15keysight_chakra.infra\x1a!keysight_chakra/infra/infra.proto\x1a$keysight_chakra/infra/annotate.proto\"\x8a\x01\n\x11ValidationRequest\x12=\n\x0einfrastructure\x18\x01 \x01(\x0b\x32%.keysight_chakra.infra.Infrastructure\x12\x36\n\x0b\x61nnotations\x18\x02 \x03(\x0b\x32!.keysight_chakra.infra.Annotation\"\x7f\n\x0fValidationError\x12\x12\n\x08optional\x18\x01 \x01(\tH\x00\x12\x0f\n\x05oneof\x18\x02 \x01(\tH\x00\x12\r\n\x03map\x18\x03 \x01(\tH\x00\x12\x1f\n\x15referential_integrity\x18\x04 \x01(\tH\x00\x12\x0f\n\x05\x63ount\x18\x05 \x01(\tH\x00\x42\x06\n\x04type\"l\n\x12ValidationResponse\x12\x36\n\x06\x65rrors\x18\x01 \x03(\x0b\x32&.keysight_chakra.infra.ValidationError\x12\x10\n\x08warnings\x18\x02 \x03(\t\x12\x0c\n\x04info\x18\x03 \x03(\t2o\n\x0cInfraService\x12_\n\x08Validate\x12(.keysight_chakra.infra.ValidationRequest\x1a).keysight_chakra.infra.ValidationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'keysight_chakra.infra.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATIONREQUEST']._serialized_start=136
  _globals['_VALIDATIONREQUEST']._serialized_end=274
  _globals['_VALIDATIONERROR']._serialized_start=276
  _globals['_VALIDATIONERROR']._serialized_end=403
  _globals['_VALIDATIONRESPONSE']._serialized_start=405
  _globals['_VALIDATIONRESPONSE']._serialized_end=513
  _globals['_INFRASERVICE']._serialized_start=515
  _globals['_INFRASERVICE']._serialized_end=626
# @@protoc_insertion_point(module_scope)
